name: do nothing useful
on:
  push: {}
  schedule:
  - cron: '0 * * * *'
jobs:
  do-nothing-onw:
  - uses: 'actions/checkout@v3'
  - run: 'ls -l'
  do-nothing-two:
  - uses: 'actions/checkout@v3'
  - run: 'ls -ltr'